mysite/addresources/urls.py
from django.conf.urls import url, include
from . import views
from addresources.models import addresources, addmatchingresources, editresources
app_name = 'addresources'
urlpatterns = [
    url(r'^addresources/$', views.create_addresources, name='create_addresources'),
    url(r'^editresources/$', views.editresourcesCreate, name='editresourcesCreate'),
    url(r'^(?P<addresources_id>[0-9]+)/details/$', views.details, name='details'),
    url(r'^(?P<addresources_id>[0-9]+)/visitor/$', views.visitor, name='visitor'),
    url(r'^(?P<addresources_id>[0-9]+)/addmatchingresources/$', views.addmatchingresourcesCreate, name='addmatchingresourcesCreate'),
    url(r'^(?P<addresources_id>[0-9]+)/delete_matches/(?P<addmatchingresources_id>[0-9]+)/$', views.delete_matches, name='delete_matches'),
    url(r'^(?P<addresources_id>[0-9]+)/delete_addresources/$', views.delete_addresources, name='delete_addresources'),
    url(r'^(?P<addresources_id>[0-9]+)/addresources_update/$', views.addresources_update, name='addresources_update'),
    url(r'^(?P<addresources_id>[0-9]+)/technologyCreate/(?P<addmatchingresources_id>[0-9]+)/$', views.technologyCreate, name='technologyCreate'),
    url(r'^(?P<addresources_id>[0-9]+)/technologyDetails/(?P<addmatchingresources_id>[0-9]+)/$', views.technologyDetails, name='technologyDetails'),
    url(r'^(?P<addresources_id>[0-9]+)/technologyUpdate/(?P<addmatchingresources_id>[0-9]+)/(?P<technologies_id>[0-9]+)$', views.technology_update, name='technology_update'),
    url(r'^dfs/$', views.dfs, name='dfs'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('webapp.urls')),
    url(r'^ridhome/getinformation', include('getinformation.urls')),
    url(r'^ridhome/', include('addresources.urls')),
    url(r'^', include('updatelog.urls')),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'})

]

mysite/webapp/urls.py
from django.conf.urls import url, include
from . import views
app_name = 'webapp'
urlpatterns = [
    url(r'^home/FAQ$', views.index, name='index'),
    url(r'^home/database$', views.database, name='database'),
    url(r'^home/searchadmin$', views.filter, name='filter'),
    url(r'^home/search$', views.filtervisitor, name='filtervisitor'),
    url(r'^home/calculator$', views.calculator, name='calculator'),
    url(r'^home/contact$', views.contact, name='contact'),
    url(r'^home', views.homepage, name='homepage')


    #url(r'^(?P<album_id>[0-9]+)$'), views.detail, name='detail'
]

mysite/addresources/models.py
from django.db import models
from django.contrib.auth.models import Permission, User
from django.core.urlresolvers import reverse


class addresources(models.Model):
    Name_of_Resource = models.CharField(max_length = 500)
    HS_Code = models.IntegerField()


    def __str__(self):
        return self.Name_of_Resource

#CASCADE(collector, field, sub_objs, using) maybe useful for selective delete
class addmatchingresources(models.Model):
    add_resources=models.ForeignKey(addresources, on_delete=models.CASCADE)
    Name_of_Matching_Resource = models.CharField(max_length = 500)
    Matching_HS_Code = models.IntegerField()
    Check_if_matches_interchangeable = models.BooleanField(default=False)
    Extraction_rate = models.DecimalField(max_digits=6,decimal_places=3)
    Source = models.CharField(max_length = 500)
    Method = models.CharField(max_length = 500,help_text="Enter field documentation")



    def __str__(self):
        return self.Name_of_Matching_Resource


class editresources(models.Model):
    Name_of_Resource = models.CharField(max_length = 500)
    HS_Code = models.IntegerField()

    def __str__(self):
        return self.Name_of_Resource


class Technologies(models.Model):
    add_resources=models.ForeignKey(addresources, on_delete=models.CASCADE)
    add_matchingresources=models.ForeignKey(addmatchingresources, on_delete=models.CASCADE)
    Method = models.TextField()
    Process = models.TextField()

    def __str__(self):
        return self.Method

#DFS onwards
def generate_adjacency_map():
    all_resources = addresources.objects.all()
    adjacency_map = {}
    for a in all_resources:
        matches = a.addmatchingresources_set.all()
        child_array = []
        if matches:
            for child in matches:
                child_array += [str(child.Matching_HS_Code)]
            adjacency_map[str(a.HS_Code)] = child_array
        else:
            adjacency_map[str(a.HS_Code)] = child_array
    return adjacency_map


def traverse(adjacency_map, starting_node, final_path):
    do_traverse(adjacency_map, starting_node, [starting_node], final_path)
    return final_path

def do_traverse(adjacency_map, current_node, current_path, final_path):
    children = adjacency_map[current_node]
    untraversed_children = []
    for child in children:
        if child not in current_path:
            untraversed_children += [child]

    if len(untraversed_children) > 0:
        for child in untraversed_children:
            do_traverse(adjacency_map, child, current_path + ["->"] + [child], final_path)
    else:
        final_path += [current_path]

mysite/addresources/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import addresources, addmatchingresources, editresources, Technologies

class addresourcesForm(forms.ModelForm):

    class Meta:
        model = addresources
        fields = ['Name_of_Resource', 'HS_Code']

class addmatchingresourcesForm(forms.ModelForm):

    class Meta:
        model = addmatchingresources
        fields = ['Name_of_Matching_Resource', 'Matching_HS_Code','Extraction_rate','Source','Method','Check_if_matches_interchangeable']

class editresourcesForm(forms.ModelForm):

    class Meta:
        model = editresources
        fields = ['Name_of_Resource', 'HS_Code']

class TechnologiesForm(forms.ModelForm):

    class Meta:
        model = Technologies
        fields = ['Method', 'Process']

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

mysite/addresources/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.shortcuts import render, get_object_or_404
from .models import addresources, addmatchingresources, editresources, Technologies
from .models import generate_adjacency_map, traverse
from .forms import addresourcesForm, addmatchingresourcesForm, editresourcesForm, TechnologiesForm, UserForm
from django.db.models import Q

from django import forms
from addresources.models import addresources


def create_addresources(request):
    form = addresourcesForm(request.POST or None)

    if form.is_valid():
        inputresource = addresources.objects.all()
        for i in inputresource:
            if i.HS_Code == form.cleaned_data.get("HS_Code"):
                context = {
                    'form': form,
                    'error_message': str(i.Name_of_Resource) + ' has already been added!',
                }
                return render(request, 'addresources/addresources.html', context)

        add_resources = form.save(commit=False)
        context = {
        'add_resources':add_resources,
        }
        add_resources.save()
        return render(request, 'webapp/details.html', context)
    return render(request, 'addresources/addresources.html', {'form':form})


def addmatchingresourcesCreate(request, addresources_id):
    form = addmatchingresourcesForm(request.POST or None)
    add_resources = get_object_or_404(addresources, pk=addresources_id)
    if form.is_valid():
        matches = add_resources.addmatchingresources_set.all()
        for m in matches:
            if m.Matching_HS_Code == form.cleaned_data.get("Matching_HS_Code"):
                context = {
                    'add_resources': add_resources,
                    'form': form,
                    'error_message': str(m.Name_of_Matching_Resource) + ' has already been added!',
                }
                return render(request, 'addresources/addmatchingresources_form.html', context)
        addmatches = form.save(commit=False)
        inputresource = addresources.objects.all()
        for i in inputresource:
            if i.HS_Code == form.cleaned_data.get("Matching_HS_Code"):
                addmatches.add_resources = add_resources
                context = {
                'add_resources': add_resources,
                }
                addmatches.save()
                return render(request, 'webapp/details.html', context)

        a = addresources(Name_of_Resource=form.cleaned_data.get("Name_of_Matching_Resource"), HS_Code=form.cleaned_data.get("Matching_HS_Code"))
        a.save()
        addmatches.add_resources = add_resources
        context = {
        'add_resources': add_resources,
        }
        addmatches.save()
        return render(request, 'webapp/details.html', context)
    context = {
        'form': form,
        'add_resources': add_resources,
    }
    return render(request, 'addresources/addmatchingresources_form.html', context)


def editresourcesCreate(request):
    form = editresourcesForm(request.POST or None)

    if form.is_valid():
        input_resources = addresources.objects.all()
        for i in input_resources:
            if i.HS_Code == form.cleaned_data.get("HS_Code"):
                context = {
                    'add_resources':i,
                }
                return render(request, 'webapp/details.html', context)

        context = {
            'form': form,
            'error_message': 'The resource is not found! Please try again!',
        }
        return render(request, 'addresources/editresources_form.html', context)
    return render(request, 'addresources/editresources_form.html', {'form':form})

def details(request, addresources_id):
    add_resources = get_object_or_404(addresources, pk=addresources_id)
    return render(request, 'webapp/details.html', {'add_resources':add_resources})

def visitor(request, addresources_id):
    add_resources = get_object_or_404(addresources, pk=addresources_id)
    return render(request, 'webapp/visitor.html', {'add_resources':add_resources})


def addresources_update(request, addresources_id):
    add_resources = get_object_or_404(addresources, pk=addresources_id)
    form = addresourcesForm(request.POST or None, instance = add_resources)
    if form.is_valid():
        inputresource = addresources.objects.all()
        for i in inputresource:
            if i.HS_Code == form.cleaned_data.get("HS_Code"):
                context = {
                    'form': form,
                    'error_message': str(i.Name_of_Resource) + ' has already been added!',
                }
                return render(request, 'addresources/addresources_update.html', context)

        add_resources = form.save(commit=False)
        context = {
            'add_resources': add_resources,
        }
        add_resources.save()
        return render(request, 'webapp/details.html', context)
    context = {
        'add_resources': add_resources,
        'form': form,
    }
    return render(request, 'addresources/addresources_update.html', context)


def delete_addresources(request, addresources_id):
    resource = addresources.objects.get(pk=addresources_id)
    resource.delete()
    all_resources = addresources.objects.all()
    return render(request, 'webapp/database.html', {'all_resources': all_resources})


def delete_matches(request, addresources_id, addmatchingresources_id):
    add_resources = get_object_or_404(addresources, pk=addresources_id)
    add_matchingresources = addmatchingresources.objects.get(pk=addmatchingresources_id)
    add_matchingresources.delete()
    return render(request, 'webapp/details.html', {'add_resources': add_resources})


def technologyCreate(request, addresources_id, addmatchingresources_id):
    form = TechnologiesForm(request.POST or None)
    add_resources = get_object_or_404(addresources, pk=addresources_id)
    add_matchingresources = get_object_or_404(addmatchingresources, pk=addmatchingresources_id)
    technology = add_matchingresources.technologies_set.all()
    if technology:
        context = {
            'add_resources': add_resources,
            'add_matchingresources': add_matchingresources,
            'form': form,
            'error_message': 'Technology has already been added. To update, please click the edit button under "View Technology"',
        }
        return render(request, 'addresources/technology_form.html', context)
    if form.is_valid():
        addtechnology = form.save(commit=False)
        addtechnology.add_resources = add_resources
        addtechnology.add_matchingresources = add_matchingresources
        context = {
        'add_resources': add_resources,
        'add_matchingresources': add_matchingresources,
        }
        addtechnology.save()
        return render(request, 'addresources/technology_details.html', context)
    context = {
        'add_resources': add_resources,
        'add_matchingresources': add_matchingresources,
        'form': form,

    }
    return render(request, 'addresources/technology_form.html', context)

def technologyDetails(request, addresources_id, addmatchingresources_id):
    add_resources = get_object_or_404(addresources, pk=addresources_id)
    add_matchingresources = addmatchingresources.objects.get(pk=addmatchingresources_id)
    #add_matchingresources = get_object_or_404(addmatchingresources, pk=addmatchingresources_id)

    context = {
        'add_resources': add_resources,
        'add_matchingresources': add_matchingresources,
    }
    return render(request, 'addresources/technology_details.html', context)

def technology_update(request, addresources_id, addmatchingresources_id, technologies_id):
    add_resources = get_object_or_404(addresources, pk=addresources_id)
    add_matchingresources = addmatchingresources.objects.get(pk=addmatchingresources_id)
    #technology = add_matchingresources.technologies_set.all()
    technology = Technologies.objects.get(pk=technologies_id)
    form = TechnologiesForm(request.POST or None, instance = technology)
    if form.is_valid():
        addtechnology = form.save(commit=False)
        addtechnology.add_resources = add_resources
        addtechnology.add_matchingresources = add_matchingresources
        context = {
        'add_resources': add_resources,
        'add_matchingresources': add_matchingresources,
        }
        addtechnology.save()
        return render(request, 'addresources/technology_details.html', context)
    context = {
        'add_resources': add_resources,
        'add_matchingresources': add_matchingresources,
        'form': form,
    }
    return render(request, 'addresources/technology_form.html', context)

def dfs(request):
    query = request.GET.get("q")
    graph = generate_adjacency_map()
    final_path = []
    path = traverse(graph, query, final_path)
    print(path)
    context = {
        'query': query,
        'path': path,
    }
    return render(request, 'addresources/dfs.html', context)


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'webapp/home.html')
    context = {
        "form": form,
    }
    return render(request, 'addresources/register.html', context)


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'addresources/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

mysite/addresources/templates/addresources/addmatchingresources_form.html
{% extends 'webapp/base.html' %}
{% block title %}Add Resources{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid w3-padding-64">

    <div class="row">

	    <!--Left side info-->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-primary"> <!--empty panel, white square-->
                <div class="panel-heading">
                    <h3>{{add_resources.Name_of_Resource}}</h3>
                </div>

                <div class="panel-body">
                    <p>Name: {{add_resources.Name_of_Resource}}</p>
                    <p>HS Code: {{add_resources.HS_Code}}</p>
                    <form action="{% url 'addresources:delete_addresources' add_resources.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="add_resources_id" value="{{ add_resources.id }}" />
                        <button type="submit" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </form>
                </div>
            </div>
        </div>

        <!--Right side info-->
        <div class="col-sm-8 col-md-9">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'addresources:details' add_resources.id %}">View All</a></li>
                <li role="presentation" class="active"><a href="{% url 'addresources:addmatchingresourcesCreate' add_resources.id %}">Add Matches</a></li>
            </ul>
            <div class="panel panel-default">
                <div class="panel-body">
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="add_resources" value="{{ add_resources }}">
                        {% include 'webapp/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Add</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

mysite/addresources/templates/addresources/addresources.html
{% extends 'webapp/base.html' %}
{% block title %}Add Resources{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid w3-padding-64">

    <div class="row">
    <div class="col-sm-12 col-md-7">

            <div class="panel panel-primary"> <!--empty panel, white square-->
            <div class="panel-heading">
            <h3>Add New Resources Into The Database</h3> </div>

                <div class="panel-body">

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post">
                        {% csrf_token %}
                        {% include 'webapp/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-5 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
</div>
{% endblock %}

mysite/addresources/templates/addresources/dfs.html
{% extends 'webapp/base.html' %}
{% block title %}Add Resources{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

	    <!--Left side info-->
        <div class="col-sm-4 col-md-3"> 	
            <div class="panel panel-primary"> <!--empty panel, white square-->
                <div class="panel-heading">
                    <h3>{{query}}</h3>
                </div>

                <div class="panel-body">
                    <h3>Possible paths for {{query}}:</h3>
                    {% for o in path %}
                        <p>                    
                        {% for i in o %}
                            {{i}}
                        {% endfor %}
                        </p>
                    {% endfor %}
                    <a href="{% url 'webapp:database' %}" class="btn btn-primary btn-sm" role="button">Back</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mysite/addresources/templates/addresources/login.html
{% extends 'webapp/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-primary"> 
            <div class="panel-heading">
            <h3>Log In</h3>
            </div>

                <div class="panel-body">
                    
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'addresources:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'addresources:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

mysite/addresources/templates/addresources/register.html
{% extends 'webapp/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-primary"> 
            <div class="panel-heading">
            <h3>Register for an Account</h3>
            </div>
                <div class="panel-body">
                    
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'webapp/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'addresources:login_user' %}">Click here</a> to log in.
                </div>
            </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

mysite/addresources/templates/addresources/technology_details.html
{% extends 'webapp/base.html' %}
{% block title %}Add Resources{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid w3-padding-64">

    <div class="row">

	    <!--Left side info-->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-primary"> <!--empty panel, white square-->
                <div class="panel-heading">
                    <h3>{{add_resources.Name_of_Resource}} -> {{add_matchingresources.Name_of_Matching_Resource}}</h3>
                </div>

                <div class="panel-body">
                    <h3>Input</h3>
                    <p>Name: {{add_resources.Name_of_Resource}}</p>
                    <p>HS Code: {{add_resources.HS_Code}}</p>
                    <h3>Output</h3>
                    <p>Name: {{add_matchingresources.Name_of_Matching_Resource}}</p>
                    <p>HS Code: {{add_matchingresources.Matching_HS_Code}}</p>
                    <a href="{% url 'addresources:details' add_resources.id %}" class="btn btn-primary btn-sm" role="button">Back</a>
                </div>
            </div>
        </div>

        <!--Right side info-->
        <div class="col-sm-8 col-md-9">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'addresources:technologyDetails' add_resources.id add_matchingresources.id %}">View Technology</a></li>
                <li role="presentation"><a href="{% url 'addresources:technologyCreate' add_resources.id add_matchingresources.id %}">Add Technology</a></li>
            </ul>
            <div class="panel panel-default">
                <div class="panel-body">
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}


                    {% if add_matchingresources.technologies_set.all %}
                        {% for technology in add_matchingresources.technologies_set.all %}
                        <a href="{% url 'addresources:technology_update' add_resources.id add_matchingresources.id technology.id %}" class="btn btn-primary btn-sm" role="button"><span class="glyphicon glyphicon-edit" aria-hidden="true" style="color:white"></span>&nbsp; Edit Technology</a>

                        <h3>Method</h3>
                        <p>{{technology.Method}}</p>
                        <h3>Process</h3>
                        <p>{{technology.Process}}</p>
                        {% endfor %}
                    {% else %}
                        <p>Technology information is not available. Kindly click 'Add Technology' tab to add new technology.</p>
                    {% endif %}

                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

mysite/addresources/templates/addresources/technology_form.html
{% extends 'webapp/base.html' %}
{% block title %}Add Resources{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid w3-padding-64">

    <div class="row">

	    <!--Left side info-->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-primary"> <!--empty panel, white square-->
                <div class="panel-heading">
                    <h3>{{add_resources.Name_of_Resource}} -> {{add_matchingresources.Name_of_Matching_Resource}}</h3>
                </div>

                <div class="panel-body">
                    <h3>Input</h3>
                    <p>Name: {{add_resources.Name_of_Resource}}</p>
                    <p>HS Code: {{add_resources.HS_Code}}</p>
                    <h3>Output</h3>
                    <p>Name: {{add_matchingresources.Name_of_Matching_Resource}}</p>
                    <p>HS Code: {{add_matchingresources.Matching_HS_Code}}</p>
                    <a href="{% url 'addresources:details' add_resources.id %}" class="btn btn-primary btn-sm" role="button">Back</a>
                </div>
            </div>
        </div>

        <!--Right side info-->
        <div class="col-sm-8 col-md-9">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'addresources:technologyDetails' add_resources.id add_matchingresources.id %}">View Technology</a></li>
                <li role="presentation" class="active"><a href="{% url 'addresources:technologyCreate' add_resources.id add_matchingresources.id %}">Add Technology</a></li>
            </ul>
            <div class="panel panel-default">
                <div class="panel-body">
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="add_resources" value="{{ add_resources }}">
                        <input type="hidden" name="add_matchingresources" value="{{ add_matchingresources }}">
                        {% include 'webapp/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}