mysite/addresources/urls.py
from django.conf.urls import url, include
from . import views
from addresources.models import addresources, addmatchingresources, editresources
app_name = 'addresources'
urlpatterns = [
    url(r'^addresources/$', views.create_addresources, name='create_addresources'),
    url(r'^editresources/$', views.editresourcesCreate, name='editresourcesCreate'),
    url(r'^(?P<addresources_id>[0-9]+)/details/$', views.details, name='details'),
    url(r'^(?P<addresources_id>[0-9]+)/visitor/$', views.visitor, name='visitor'),
    url(r'^(?P<addresources_id>[0-9]+)/addmatchingresources/$', views.addmatchingresourcesCreate, name='addmatchingresourcesCreate'),
    url(r'^(?P<addresources_id>[0-9]+)/delete_matches/(?P<addmatchingresources_id>[0-9]+)/$', views.delete_matches, name='delete_matches'),
    url(r'^(?P<addresources_id>[0-9]+)/delete_addresources/$', views.delete_addresources, name='delete_addresources'),
    url(r'^(?P<addresources_id>[0-9]+)/addresources_update/$', views.addresources_update, name='addresources_update'),
    url(r'^(?P<addresources_id>[0-9]+)/technologyCreate/(?P<addmatchingresources_id>[0-9]+)/$', views.technologyCreate, name='technologyCreate'),
    url(r'^(?P<addresources_id>[0-9]+)/technologyDetails/(?P<addmatchingresources_id>[0-9]+)/$', views.technologyDetails, name='technologyDetails'),
    url(r'^(?P<addresources_id>[0-9]+)/technologyUpdate/(?P<addmatchingresources_id>[0-9]+)/(?P<technologies_id>[0-9]+)$', views.technology_update, name='technology_update'),
    url(r'^dfs/$', views.dfs, name='dfs'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('webapp.urls')),
    url(r'^ridhome/getinformation', include('getinformation.urls')),
    url(r'^ridhome/', include('addresources.urls')),
    url(r'^', include('updatelog.urls')),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'})

]

mysite/webapp/urls.py
from django.conf.urls import url, include
from . import views
app_name = 'webapp'
urlpatterns = [
    url(r'^home/FAQ$', views.index, name='index'),
    url(r'^home/database$', views.database, name='database'),
    url(r'^home/searchadmin$', views.filter, name='filter'),
    url(r'^home/search$', views.filtervisitor, name='filtervisitor'),
    url(r'^home/calculator$', views.calculator, name='calculator'),
    url(r'^home/contact$', views.contact, name='contact'),
    url(r'^home', views.homepage, name='homepage')


    #url(r'^(?P<album_id>[0-9]+)$'), views.detail, name='detail'
]

mysite/webapp/views.py
from django.shortcuts import render
from addresources.models import addresources
from updatelog import views

#from django.contrib.auth import authenticate, login
#from django.views.generic import View
#from .forms import UserForm

#class UserFormView(View):
    #form_class = UserForm
    #template_name = 'webapp/registration.html'

def index(request):
    return render(request, 'webapp/home.html') # this two parameters are compulsory

def database(request):
    all_resources=addresources.objects.all()
    return render(request, 'webapp/database.html', {'all_resources':all_resources})

def filter(request):
    all_resources=addresources.objects.all()
    return render(request, 'webapp/filter.html', {'all_resources':all_resources})

def calculator(request):
    all_resources=addresources.objects.all()
    return render(request, 'webapp/calculator.html', {'all_resources':all_resources})

def homepage(request):
    return render(request, 'webapp/homepage.html')

def filtervisitor(request):
    all_resources=addresources.objects.all()
    return render(request, 'webapp/filtervisitor.html', {'all_resources':all_resources})

def contact(request):
    return render(request, 'webapp/contactus.html')

def updatelog(request):
    return render(request, 'updatelog/about.html')

mysite/webapp/templates/webapp/base.html
<!DOCTYPE html>
<html>
<title>RID</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<style>
body {font-family: "Roboto", sans-serif}
.w3-bar-block .w3-bar-item{padding:16px;font-weight:bold}
</style>
<body>



{% load static %}

<!-- Navbar -->
</div>

<div class="w3-bar w3-top w3-black w3-large" style="z-index:4">
  <button class="w3-bar-item w3-button w3-hide-large w3-hover-none w3-hover-text-light-grey" onclick="w3_open();"><i class="fa fa-bars"></i>  Menu</button>
  <span class="w3-bar-item w3-right"><img src="{% static 'webapp/images/rid.png' %}" width="60" height="42"></span>
</div>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:200px;" id="mySidebar"><br>
  <div class="w3-bar-block w3-padding-32">
    <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>  Close Menu</a>
    <a href="{% url 'webapp:homepage' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-home fa-fw"></i> Home</a>
    <a href="{% url 'webapp:index' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-eye fa-fw"></i> FAQ</a>
    <a href="{% url 'webapp:filtervisitor' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-search fa-fw"></i> Search</a>
    <a href="{% url 'webapp:calculator' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bell fa-fw"></i> Recycling calculator</a>
    <a href="{% url 'webapp:contact' %}" class="w3-bar-item w3-button w3-padding"> <i class="fa fa-male fa-fw"></i> Contact us!</a>
    <a href="{% url 'about'%}" class="w3-bar-item w3-button w3-padding"> <i class="fa fa-cloud fa-fw"></i> Update Log</a>
    <a href="#" class="w3-red w3-bar-item w3-button w3-padding"></i> ADMIN</a>
    <a href="{% url 'addresources:create_addresources' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bullseye fa-fw"></i> Add Resource</a>
    <a href="{% url 'webapp:database' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-diamond fa-fw"></i> Database</a>
    <a href="{% url 'webapp:filter' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-search fa-fw"></i> Search</a>
  </div>
</nav>

<script>
// Get the Sidebar
var mySidebar = document.getElementById("mySidebar");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidebar, and add overlay effect
function w3_open() {
    if (mySidebar.style.display === 'block') {
        mySidebar.style.display = 'none';
        overlayBg.style.display = "none";
    } else {
        mySidebar.style.display = 'block';
        overlayBg.style.display = "block";
    }
}

// Close the sidebar with the close button
function w3_close() {
    mySidebar.style.display = "none";
    overlayBg.style.display = "none";
}
</script>


	<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" id="myOverlay"></div>

	<div class="w3-main" style="margin-left:250px;">

	<div id="myTop" class="w3-container w3-top w3-theme w3-large">
	  <p><i class="fa fa-bars w3-button w3-teal w3-hide-large w3-xlarge" onclick="w3_open()"></i>
	  <span id="myIntro" class="w3-hide">W3.CSS: Introduction</span></p>
	</div>

  </div>
</nav>

<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" id="myOverlay"></div>


<div class="w3-main" style="margin-left:256px;">

	{% block body %}
	{% endblock %}
</body>
</html>

mysite/webapp/templates/webapp/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}RID{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href='https://fonts.googleapis.com/css?family=Tangerine' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'webapp/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'webapp/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'webapp:index' %}">RID</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'addresources:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'addresources:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

mysite/webapp/templates/webapp/calculator.html
{% extends 'webapp/base.html' %}
{% block body %}

{% load static %}

<div class="w3-container w3-content w3-left w3-padding-64" style="max-width:600px" >
    <h2 class="w3-wide">Recycling calculator</h2>
    <p class="w3-opacity"><i>Find out how much potential tax rebates you can get from recycling!<br></i></p>
    <h4 class="w3-justify"> As an initiative to promote zero wastage, SIMTECH in collaboration with NEA is devising a waste tax relief programme which would allow companies to obtain tax relief should they meet certain recycling criterias.
                      <br>Find out how much tax relief you or your organisation can possibly get from recycling here!
                    </h4>

        </div>

<html>
<title>Fahrenheit to Celcius Temperature Converter</title>
<body>

<h2>Recycling calculator</h2>
<p>Select type of Waste: </p>
<select>
  <option id="apple">Plastic</option>
  <option id="orange">Food</option>
  <option id="pineapple">Paper</option>

</select>



<script>
function myFunction() {
    document.getElementById("apple").text = "newTextForApple";
}
</script>

</body>
</html>

<p><br>Enter the weight and type of input you would like to recycle: </p>

<p>
  <label>Weight</label>
  <input id="inputFahrenheit" type="number" placeholder=" in KG.." oninput="temperatureConverter(this.value)" onchange="temperatureConverter(this.value)">
</p>
<p>Potential Savings: $<span id="outputCelcius"></span></p>

<script>
function temperatureConverter(valNum) {
  valNum = parseFloat(valNum);
  document.getElementById("outputCelcius").innerHTML=(valNum-32)/1.8;
}
</script>
<h2>Waste relief table</h2>
<img src="{% static 'webapp/images/complex.png' %}"  width="600" height="300">
</body>
</html>


{% endblock %}

mysite/webapp/templates/webapp/database.html
{% extends 'webapp/base.html' %}
{% block body %}

	<style>
		table {
		    font-family: arial, sans-serif;
		    border-collapse: collapse;
		    width: 100%;
		}

		td, th {
		    border: 1px solid black;
		    text-align: left;
		    padding: 8px;
		}

		tr:nth-child(even) {
		    background-color: lightblue;
		}

	</style>
	<div class="col-sm-10 col-md-3 w3-padding-64">
	<form role="search" method="get" action="{% url 'addresources:dfs' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search Path</button>
    </form>
		<table>

			  <tr>
			    <th>Name</th>
			    <th>HS Code</th>
			    <th>Match1</th>
			    <th>Match1</th>
			    <th>Match2</th>
			    <th>Match3</th>
			    <th>Match4</th>
			    <th>Match5</th>
			    <th>Match6</th>
			  </tr>

			{% for resources in all_resources %}
				<tr>
					<div class="tooltip">
					<td><a href="{% url 'addresources:details' resources.id %}" data-toggle="tooltip" data-placement="bottom" title="Potential Matches: ...">{{resources.Name_of_Resource}}</a></td>
					</div>
				    <td>{{resources.HS_Code}}</td>
				    {% for match in resources.addmatchingresources_set.all %}
				    	<td>{{match.Name_of_Matching_Resource}}</td>
							
				    {% endfor %}
				</tr>
			{% endfor %}
		</table>
	</div>
	<script>
		$(document).ready(function(){
		    $('[data-toggle="tooltip"]').tooltip();
		});
	</script>
{% endblock %}

mysite/webapp/templates/webapp/details.html
{% extends 'webapp/base.html' %}
{% block title %}Add Resources{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid w3-padding-64"  >

    <div class="row">

        <div class="col-sm-4 col-md-3">
            <!--Left side info-->
            <div class="panel panel-primary"> <!--empty panel, white square-->
                <div class="panel-heading">
                    <h3>
                    <a href= "{% url 'addresources:addresources_update' add_resources.id %}">
                      <span class="glyphicon glyphicon-edit" aria-hidden="true" style="color:white"></span>
                    </a>
                    &nbsp;{{add_resources.Name_of_Resource}}
                    </h3>
                </div>

                <div class="panel-body">
                    <p>Name: {{add_resources.Name_of_Resource}}</p>
                    <p>HS Code: {{add_resources.HS_Code}}</p>
                    <form action="{% url 'addresources:delete_addresources' add_resources.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="add_resources_id" value="{{ add_resources.id }}" />
                        <button type="submit" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </form>
                </div>
            </div>
        </div>

        <!--Right side info-->
        <div class="col-sm-8 col-md-9">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'addresources:details' add_resources.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'addresources:addmatchingresourcesCreate' add_resources.id %}">Add Matches</a></li>
            </ul>
                <div class="panel panel-default">
                    <div class="panel-body">

                        <h3>All Matches</h3>

                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}

                        <table class="table">
                            <thead>
                            <tr>
                                <th>Name of Matches</th>
                                <th>Matching HS Code</th>
                                <th>Extraction rate</th>
                                <th>Source</th>
                                <th>Method</th>
                                <th>Action</th>

                            </tr>
                            </thead>
                            <tbody>
                            {% for addmatches in add_resources.addmatchingresources_set.all %}
                                <tr>
                                    <td><a href="{% url 'addresources:technologyDetails' add_resources.id addmatches.id %}">{{ addmatches.Name_of_Matching_Resource }}</a></td>
                                    <td>{{ addmatches.Matching_HS_Code }}</td>
                                    <td>{{ addmatches.Extraction_rate }}</td>
                                    <td>
                                      {{ addmatches.Source }}


                                    </td>
                                    <td>{{ addmatches.Method }}</td>

                                    <td>
                                        <form action="{% url 'addresources:delete_matches' add_resources.id addmatches.id %}" method="post" style="display: inline;">
                                            {% csrf_token %}
                                            <input type="hidden" name="addmatches_id" value="{{ addmatches.id }}" />
                                            <button type="submit" class="btn btn-danger btn-xs">
                                                <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>

        </div>
    </div>
</div>
{% endblock %}

mysite/webapp/templates/webapp/filter.html
{% extends 'webapp/base.html' %}
{% block body %}

{% load static %}

<!DOCTYPE html>
<html>
<head>
<style>
* {
  box-sizing: border-box;
}

#myInput {
  background-image: url('https://cdn1.iconfinder.com/data/icons/hawcons/32/698627-icon-111-search-512.png');
  background-position: 10px 12px;
  background-repeat: no-repeat;
  width: 100%;
  font-size: 16px;
  padding: 12px 20px 12px 40px;
  border: 1px solid #ddd;
  margin-bottom: 12px;
}

#myUL {
  list-style-type: none;
  padding: 0;
  margin: 0;
}

#myUL li a {
  border: 1px solid #ddd;
  margin-top: -1px; /* Prevent double borders */
  background-color: #f6f6f6;
  padding: 12px;
  text-decoration: none;
  font-size: 18px;
  color: black;
  display: block
}

#myUL li a.header {
  background-color: #e2e2e2;
  cursor: default;
}

#myUL li a:hover:not(.header) {
  background-color: #eee;
}
</style>
</head>
<body>

<h2>Database</h2>

<input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for resource.." title="Type in a name">

      <ul id="myUL">
        {% for resources in all_resources %}
          <li><a href="{% url 'addresources:details' resources.id %}"  title="Potential Matches: ...">{{resources.Name_of_Resource}}</a></li>
        {% endfor %}
        </ul>



<script>
function myFunction() {
    var input, filter, ul, li, a, i;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    ul = document.getElementById("myUL");
    li = ul.getElementsByTagName("li");
    for (i = 0; i < li.length; i++) {
        a = li[i].getElementsByTagName("a")[0];
        if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
            li[i].style.display = "";
        } else {
            li[i].style.display = "none";

        }
    }
}
</script>

</body>
</html>


{% endblock %}

mysite/webapp/templates/webapp/filtervisitor.html
{% extends 'webapp/base.html' %}
{% block body %}

{% load static %}

<!DOCTYPE html>
<html>
<head>
<style>
* {
  box-sizing: border-box;
}

#myInput {
  background-image: url('https://cdn1.iconfinder.com/data/icons/hawcons/32/698627-icon-111-search-512.png');
  background-position: 10px 12px;
  background-repeat: no-repeat;
  width: 100%;
  font-size: 16px;
  padding: 12px 20px 12px 40px;
  border: 1px solid #ddd;
  margin-bottom: 12px;
}

#myUL {
  list-style-type: none;
  padding: 0;
  margin: 0;
}

#myUL li a {
  border: 1px solid #ddd;
  margin-top: -1px; /* Prevent double borders */
  background-color: #f6f6f6;
  padding: 12px;
  text-decoration: none;
  font-size: 18px;
  color: black;
  display: block
}

#myUL li a.header {
  background-color: #e2e2e2;
  cursor: default;
}

#myUL li a:hover:not(.header) {
  background-color: #eee;
}
</style>
</head>
<body>

<h2>Database</h2>

<input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for resource.." title="Type in a name">

      <ul id="myUL">
        {% for resources in all_resources %}
          <li><a href="{% url 'addresources:visitor' resources.id %}"  title="Potential Matches: ...">{{resources.Name_of_Resource}}</a></li>
        {% endfor %}
        </ul>



<script>
function myFunction() {
    var input, filter, ul, li, a, i;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    ul = document.getElementById("myUL");
    li = ul.getElementsByTagName("li");
    for (i = 0; i < li.length; i++) {
        a = li[i].getElementsByTagName("a")[0];
        if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
            li[i].style.display = "";
        } else {
            li[i].style.display = "none";

        }
    }
}
</script>

</body>
</html>


{% endblock %}

mysite/webapp/templates/webapp/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-3">{{ field.label_tag }}</label>
        <div class="col-sm-2">{{ field }}</div>
    </div>
{% endfor %}

mysite/webapp/templates/webapp/visitor.html
{% extends 'webapp/base.html' %}
{% block title %}Add Resources{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid w3-padding-64"  >

    <div class="row">

        <div class="col-sm-4 col-md-3">
            <!--Left side info-->
            <div class="panel panel-primary"> <!--empty panel, white square-->
                <div class="panel-heading">
                    <h3>
                    <a href= "{% url 'addresources:addresources_update' add_resources.id %}">
                      <span class="glyphicon glyphicon-edit" aria-hidden="true" style="color:white"></span>
                    </a>
                    &nbsp;{{add_resources.Name_of_Resource}}
                    </h3>
                </div>

                <div class="panel-body">
                    <p>Name: {{add_resources.Name_of_Resource}}</p>
                    <p>HS Code: {{add_resources.HS_Code}}</p>
                    <form action="{% url 'addresources:delete_addresources' add_resources.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="add_resources_id" value="{{ add_resources.id }}" />
                        <button type="submit" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </form>
                </div>
            </div>
        </div>



        <div class="col-sm-8 col-md-9">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">

            </ul>
                <div class="panel panel-default">
                    <div class="panel-body">

                      <h2>Technology</h2>
                      <p>Please select technology: </p>
                      <select id="test" name="form_select" onchange="showDiv(this)">
                          <option value="" disabled selected>Select your option</option>
                          <option value="1">Anaerobic Digestion</option>
                        </select>
                    </div>
                </div>
        <!--Right side info-->
        <div id="hidden_div"  style="display:none;" class="col-sm-8 col-md-9">

                <div class="panel panel-default">
                    <div class="panel-body">

                        <h3>All Matches</h3>

                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}

                        <table class="table">
                            <thead>
                            <tr>
                                <th>Name of Matches</th>
                                <th>Matching HS Code</th>
                                <th>Extraction rate</th>
                                <th>Source</th>



                            </tr>
                            </thead>
                            <tbody>
                            {% for addmatches in add_resources.addmatchingresources_set.all %}
                                <tr>
                                    <td><a href="{% url 'addresources:technologyDetails' add_resources.id addmatches.id %}">{{ addmatches.Name_of_Matching_Resource }}</a></td>
                                    <td>{{ addmatches.Matching_HS_Code }}</td>
                                    <td>{{ addmatches.Extraction_rate }} %</td>
                                    <td>{{ addmatches.Source }}</td>




                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-body">


                        <h3>Parameters</h3>

                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}

                        <table class="table">
                            <thead>
                            <tr>
                                <th>Condition</th>
                                <th>Value</th>
                            </tr>
                            </thead>
                            <tbody>


                              <tr>
                                <td>Temperature</td>
                                <td></td>
                              </tr>
                              <tr>
                                <td>Catalyst</td>
                                <td></td>
                              </tr>


                            </tbody>
                        </table>
                    </div>
                </div>




        </div>
    </div>
</div>

<script type="text/javascript">
function showDiv(select){
   if(select.value==1){
    document.getElementById('hidden_div').style.display = "block";
   } else{
    document.getElementById('hidden_div').style.display = "none";
   }
}
</script>

{% endblock %}